Long_Reads_dir:
    /home/daiwei/graduate/Oryza_sativa/CRR306311.fasta
Short_reads_dir1:
    /home/daiwei/graduate/Oryza_sativa/CRR306398_f1.fq.gz
Short_reads_dir2:
    /home/daiwei/graduate/Oryza_sativa/CRR306398_r2.fq.gz
Number_of_threads: 
    10
Maximum_memory:
    10G
Seed_dir:
    /home/daiwei/graduate/Oryza_sativa/NC_011033.1.fasta
Long_reads_platform:
    ont
Long_reads_type:
    --nano-raw
Estimated_genome_size:
    0.5m    
